// XXX: This file could be autogenerated based on user selection (enable_upx_compression)
//      also, is this still needed in c++11?
#pragma once

// Allow UPX Compression (prevents use of TLS callbacks in boost::thread)
extern "C" { void tss_cleanup_implemented(void){} }
